### ISSUE TITLE
Accessibility concerns

### ISSUE THREAD

**Issue by rpearce** [nix-community/builtwithnix.org#18]
Result of running the axe browser plugin:
<img width="1179" alt="result of axe plugin execution on builtwithnix.org" src="https://user-images.githubusercontent.com/592876/82450358-1ff5ce80-9a9c-11ea-84a1-6da567b58cab.png">

Firefox developer edition's a11y analysis:
<img width="1440" alt="Firefox developer edition's a11y analysis" src="https://user-images.githubusercontent.com/592876/82450478-4582d800-9a9c-11ea-9a95-dddc9ffee692.png">

If y'all want help with this, let me know, for this is very much within my skillset, and I can put up a PR. But first: I want to know if help here is desired before spending my time on it.

**Comment by Mic92** [comment]
Bring it on!

**Comment by zimbatm** [comment]
Agreed, it's a great initiative.

**Comment by rpearce** [comment]
Rock on. I'll put it on my to-do list.

**Comment by rpearce** [comment]
Fear not! This is still on my to-do list. I've been focusing on https://github.com/rpearce/image-zoom/pull/244.
