### ISSUE TITLE
Remove blindtext from testimonials

### ISSUE THREAD

**Issue by Mic92** [nix-community/builtwithnix.org#6]
Just a reminder so you not forget to remove the lorem ipsum snippets from the testimonials section:

https://github.com/nix-community/builtwithnix.org/blob/4c2c8b97545d99940de286bba54b928565300694/index.html#L410

**Comment by manveru** [comment]
So to move this forward, maybe @shlevy @sorki @smilliken @vaibhavsagar @ckauhaus @grahamc wouldn't mind to provide some quotes we could use?

**Comment by bobvanderlinden** [comment]
Maybe also ask @garbas for a quote as he is using it at Mozilla.

**Comment by Mic92** [comment]
I think he was about to leave.

**Comment by grahamc** [comment]
Is that public enough of information to publish on the internet? Maybe should delete that comment.

**Comment by rpearce** [comment]
Reckon this issue can be closed? I don't see any placeholder text anywhere in the project

**Comment by Mic92** [comment]
Maybe we can also get people from shopify to write a testimonial.
